---
- name: Ensure group "nginx-exp" exists
  become: true
  group:
    name: nginx-exp
    state: present
- name: Adds the user 'nginx-exp' to the wheel group
  become: true
  user:
    name: nginx-exp
    shell: /bin/bash
    group: nginx-exp
- name: Download nginx-exporter
  become: true
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /tmp/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    mode: 0550
- name: ensure nginx-exp directory exists
  become: true
  file:
    path: /usr/local/bin/nginx-prometheus-exporter
    state: directory
- name: Extract nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
  become: true
  unarchive:
    src: /tmp/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    remote_src: true
    dest: /usr/local/bin/nginx-prometheus-exporter
- name: Copies the nginx_exporter.service template
  template:
    src: files/nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
    owner: root
    group: root
    mode: 0644
  become: true
- name: Make sure nginx_exporter service is running
  become: true
  systemd:
    state: started
    name: nginx_exporter
