---
- name: tests if nginx_exporter is up
  action: uri url=http://localhost:9113/metrics return_content=yes
  register: webpage
- fail:
    msg: 'nginx_exporter is not up'
  when: "'nginx_up 1' not in webpage.content"
- name: test if nginx is up
  action: uri url=http://localhost status_code=200
  register: webpage
- fail:
    msg: 'nginx is not up'
  when: "webpage.status != 200"
